name: laregione
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  provider: ^5.0.0
  google_fonts: ^2.1.0
  material_design_icons_flutter: ^4.0.5955
  persistent_bottom_nav_bar: ^4.0.2
  http: ^0.13.3
  fluttertoast: ^8.0.7


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
<<<<<<< HEAD

    #Profiles
    - assets/images/
    #Food
    - assets/food/

    - assets/topics/

    - assets/dummies/


    ###################---------------------- Custom Apps -------------------------#################

    ##Grocery
    - assets/grocery/


    #Illustration
    - assets/illustration/hotel/
    - assets/illustration/shopping/


    #Icons
    - assets/icons/

    #Other
    - assets/other/
    #Designs
    - assets/design/
=======
>>>>>>> ui
    - assets/
